spring.application.name=vcs-backend-worker

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

app.worker.redis.channel=${WORKER_CHANNEL:vcs.diff.jobs}
app.worker.redis.result-channel=${WORKER_RESULT_CHANNEL:vcs.diff.results}
app.worker.redis.listener-enabled=${WORKER_LISTENER_ENABLED:true}
